local addonName, ns = ...
local L = ns.L
local locale = GetLocale()
-- =========================================================
-- 7. 法语 (frFR)
-- =========================================================
if locale == "frFR" then
L["AddonName"] = "LorisID |cFF00FF00[Minuit]|r"
L["Init_Loaded"] = "LorisID initialise. API Minuit 12.0 prete."
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r Parametres"

L["Control"] = "Controle"
L["EnableModule"] = "Activer le module"
L["Debug Mode"] = "Mode debogage"
L["ID Display Settings"] = "Parametres d'affichage d'ID"
L["Item"] = "Objet"
L["Spell"] = "Sort"
L["Petspell"] = "Sort de familier"
L["Unit"] = "Unite"
L["Quest"] = "Quete"
L["Achievement"] = "Haut fait"
L["Currency"] = "Monnaie"
L["Mount"] = "Monture"
L["Toy"] = "Jouet"
L["Talent"] = "Talent"
L["Companion"] = "Compagnon"
L["Object"] = "Objet du monde"
L["Battlepet"] = "Mascotte de combat"
L["Instance"] = "Instance"
L["Recipe"] = "Recette"
L["Macro"] = "Macro"
L["Pvp"] = "Bagarre JcJ"
L["Minimap"] = "Mini-carte"
L["Icon"] = "Icone"
L["Set"] = "Ensemble"
L["Visual"] = "Transmogrification"
L["Performance & Cache"] = "Performance & Cache"
L["Enable high-performance LRU cache"] = "Activer le cache LRU haute performance"
L["Cache Size Limit"] = "Limite de taille du cache"
L["Performance Audit Warning Threshold"] = "Seuil d'alerte d'audit de performance"

L["Spell ID"] = "ID du sort"
L["Petspell ID"] = "ID du sort de familier"
L["Item ID"] = "ID de l'objet"
L["Unit ID"] = "ID de l'unite"
L["NPC ID"] = "ID du PNJ"
L["Quest ID"] = "ID de la quete"
L["Achievement ID"] = "ID du haut fait"
L["Currency ID"] = "ID de la monnaie"
L["Mount ID"] = "ID de la monture"
L["Toy ID"] = "ID du jouet"
L["Companion ID"] = "ID du compagnon"
L["Object ID"] = "ID de l'objet du monde"
L["Battlepet ID"] = "ID de mascotte"
L["Instance ID"] = "ID de l'instance"
L["Recipe ID"] = "ID de recette"
L["Macro ID"] = "ID de macro"
L["Pvp ID"] = "ID de bagarre JcJ"
L["Minimap ID"] = "ID de mini-carte"
L["Icon ID"] = "ID d'icone"
L["Talent ID"] = "ID de talent"
L["Set ID"] = "ID d'ensemble"
L["Equipment Set ID"] = "ID d'ensemble d'equipement"
L["Visual ID"] = "ID de transmogrification"

L["Item_Level"] = "Niveau d'objet"
L["Stack_Size"] = "Taille de pile"
L["Item_Price"] = "Prix de vente"
L["Unit_Classification"] = "Classification"
L["GUID"] = "GUID"
L["Target of"] = "Cible de"
L["Expansion"] = "Extension"
L["Count"] = "Nombre"
L["SecretValueBlocked"] = "Bloque : tentative d'acces a une valeur secrete en combat."
L["RestrictedEnvironment"] = "Environnement restreint (Mythique+/JcJ/Combat). Certains elements verrouilles."
L["PerfAlert"] = "Alerte performance : le temps d'execution depasse le seuil !"

L["Cmd_Config"] = "ouvrir les parametres"
L["Cmd_Cache"] = "vider le cache"
L["Cmd_Version"] = "afficher la version"
L["Cmd_Help"] = "Aide des commandes"
L["Clear All"] = "Tout vider"
L["Toggle Debug Mode"] = "Basculer le mode debogage"
L["Combat Ended"] = "Combat termine, mode d'audit de securite desactive."
L["Engine Started"] = "Moteur central Minuit 12.0 demarre."
L["Audit Report"] = "Rapport d'audit d'objet"
L["Scanning Auras"] = "Analyse des donnees d'aura 12.0 pour l'unite %s ..."
L["Settings_Enable_Desc"] = "Activer/desactiver toutes les infobulles LorisID"
L["Settings_Debug_Desc"] = "Activer la sortie d'audit 12.0 C_AddOnProfiler"
L["Settings_Cache_Desc"] = "Reduire la latence en ville/combat a grande echelle"
L["Settings_CacheSize_Desc"] = "L'eviction LRU se declenche au-dela de ce nombre"
L["Settings_Threshold_Desc"] = "Avertir dans le chat si le temps d'execution depasse"
L["Items Count"] = "elements"
end

-- =========================================================
-- 8. 西班牙语 (esES / esMX)
-- =========================================================
if locale == "esES" or locale == "esMX" then
L["AddonName"] = "LorisID |cFF00FF00[Medianoche]|r"
L["Init_Loaded"] = "LorisID inicializado. API Medianoche 12.0 lista."
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r Configuracion"

L["Control"] = "Control"
L["EnableModule"] = "Activar modulo"
L["Debug Mode"] = "Modo depuracion"
L["ID Display Settings"] = "Configuracion de visualizacion de ID"
L["Item"] = "Objeto"
L["Spell"] = "Hechizo"
L["Petspell"] = "Hechizo de mascota"
L["Unit"] = "Unidad"
L["Quest"] = "Mision"
L["Achievement"] = "Logro"
L["Currency"] = "Moneda"
L["Mount"] = "Montura"
L["Toy"] = "Juguete"
L["Talent"] = "Talento"
L["Companion"] = "Companero"
L["Object"] = "Objeto del mundo"
L["Battlepet"] = "Mascota de duelo"
L["Instance"] = "Estancia"
L["Recipe"] = "Receta"
L["Macro"] = "Macro"
L["Pvp"] = "Pelea JcJ"
L["Minimap"] = "Minimapa"
L["Icon"] = "Icono"
L["Set"] = "Conjunto"
L["Visual"] = "Transfiguracion"
L["Performance & Cache"] = "Rendimiento y cache"
L["Enable high-performance LRU cache"] = "Activar cache LRU de alto rendimiento"
L["Cache Size Limit"] = "Limite de tamano de cache"
L["Performance Audit Warning Threshold"] = "Umbral de alerta de auditoria de rendimiento"

L["Spell ID"] = "ID de hechizo"
L["Petspell ID"] = "ID de hechizo de mascota"
L["Item ID"] = "ID de objeto"
L["Unit ID"] = "ID de unidad"
L["NPC ID"] = "ID de PNJ"
L["Quest ID"] = "ID de mision"
L["Achievement ID"] = "ID de logro"
L["Currency ID"] = "ID de moneda"
L["Mount ID"] = "ID de montura"
L["Toy ID"] = "ID de juguete"
L["Companion ID"] = "ID de companero"
L["Object ID"] = "ID de objeto del mundo"
L["Battlepet ID"] = "ID de mascota"
L["Instance ID"] = "ID de estancia"
L["Recipe ID"] = "ID de receta"
L["Macro ID"] = "ID de macro"
L["Pvp ID"] = "ID de pelea JcJ"
L["Minimap ID"] = "ID de minimapa"
L["Icon ID"] = "ID de icono"
L["Talent ID"] = "ID de talento"
L["Set ID"] = "ID de conjunto"
L["Equipment Set ID"] = "ID de conjunto de equipo"
L["Visual ID"] = "ID de transfiguracion"

L["Item_Level"] = "Nivel de objeto"
L["Stack_Size"] = "Tamano de pila"
L["Item_Price"] = "Precio de venta"
L["Unit_Classification"] = "Clasificacion"
L["GUID"] = "GUID"
L["Target of"] = "Objetivo de"
L["Expansion"] = "Expansion"
L["Count"] = "Cantidad"
L["SecretValueBlocked"] = "Bloqueado: intento de operar sobre un valor secreto en combate."
L["RestrictedEnvironment"] = "Entorno restringido (Mitica+/JcJ/Combate). Algunos elementos bloqueados."
L["PerfAlert"] = "Alerta de rendimiento: el tiempo de ejecucion supera el umbral!"

L["Cmd_Config"] = "abrir configuracion"
L["Cmd_Cache"] = "limpiar cache"
L["Cmd_Version"] = "mostrar version"
L["Cmd_Help"] = "Ayuda de comandos"
L["Clear All"] = "Limpiar todo"
L["Toggle Debug Mode"] = "Alternar modo depuracion"
L["Combat Ended"] = "Combate terminado, modo auditoria de seguridad desactivado."
L["Engine Started"] = "Motor central Medianoche 12.0 iniciado."
L["Audit Report"] = "Informe de auditoria de objeto"
L["Scanning Auras"] = "Escaneando auras 12.0 para unidad %s ..."
L["Settings_Enable_Desc"] = "Activar/desactivar todas las descripciones de LorisID"
L["Settings_Debug_Desc"] = "Activar salida de auditoria C_AddOnProfiler 12.0"
L["Settings_Cache_Desc"] = "Reducir el lag en ciudades/combate a gran escala"
L["Settings_CacheSize_Desc"] = "La expulsion LRU se activa por encima de esta cantidad"
L["Settings_Threshold_Desc"] = "Avisar en chat si el tiempo de ejecucion supera este valor"
L["Items Count"] = "elementos"
end

-- =========================================================
-- 9. 俄语 (ruRU)
-- =========================================================
if locale == "ruRU" then
L["AddonName"] = "LorisID |cFF00FF00[Polnoch]|r"
L["Init_Loaded"] = "LorisID inicializirovan. API Polnoch 12.0 gotov."
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r Nastroiki"

L["Control"] = "Upravlenie"
L["EnableModule"] = "Vkluchit modul"
L["Debug Mode"] = "Rezhim otladki"
L["ID Display Settings"] = "Nastroiki otobrazheniya ID"
L["Item"] = "Predmet"
L["Spell"] = "Zaklinanie"
L["Petspell"] = "Zaklinanie pitomtsa"
L["Unit"] = "Yedinitsa"
L["Quest"] = "Zadanie"
L["Achievement"] = "Dostizhenie"
L["Currency"] = "Valuta"
L["Mount"] = "Transport"
L["Toy"] = "Igrushka"
L["Talent"] = "Talant"
L["Companion"] = "Kompanon"
L["Object"] = "Obekt"
L["Battlepet"] = "Boevoi pitomets"
L["Instance"] = "Podzemelye"
L["Recipe"] = "Retscept"
L["Macro"] = "Makros"
L["Pvp"] = "PvP-posoedinok"
L["Minimap"] = "Minikarta"
L["Icon"] = "Znachok"
L["Set"] = "Komplekt"
L["Visual"] = "Transfiguratsiya"
L["Performance & Cache"] = "Proizvoditelnost i kesh"
L["Enable high-performance LRU cache"] = "Vkluchit LRU-kesh"
L["Cache Size Limit"] = "Limit razmera kesha"
L["Performance Audit Warning Threshold"] = "Porog proizvoditelnosti"

L["Spell ID"] = "ID zaklinaniya"
L["Petspell ID"] = "ID zaklinaniya pitomtsa"
L["Item ID"] = "ID predmeta"
L["Unit ID"] = "ID yedinitsy"
L["NPC ID"] = "ID NPC"
L["Quest ID"] = "ID zadaniya"
L["Achievement ID"] = "ID dostizheniya"
L["Currency ID"] = "ID valuty"
L["Mount ID"] = "ID transporta"
L["Toy ID"] = "ID igrushki"
L["Companion ID"] = "ID kompanona"
L["Object ID"] = "ID obekta"
L["Battlepet ID"] = "ID pitomtsa"
L["Instance ID"] = "ID podzemelya"
L["Recipe ID"] = "ID retsepta"
L["Macro ID"] = "ID makrosa"
L["Pvp ID"] = "ID PvP-posoedinka"
L["Minimap ID"] = "ID minikarty"
L["Icon ID"] = "ID znachka"
L["Talent ID"] = "ID talanta"
L["Set ID"] = "ID komplekta"
L["Equipment Set ID"] = "ID komplekta snaryazheniya"
L["Visual ID"] = "ID transfiguratsii"

L["Item_Level"] = "Uroven predmeta"
L["Stack_Size"] = "Razmer steka"
L["Item_Price"] = "Tsena prodazhi"
L["Unit_Classification"] = "Klassifikatsiya"
L["GUID"] = "GUID"
L["Target of"] = "Tsel"
L["Expansion"] = "Dopolnenie"
L["Count"] = "Kolichestvo"
L["SecretValueBlocked"] = "Zablokirovano: popytka dostupa k sekretnomu znacheniu v bou."
L["RestrictedEnvironment"] = "Ogranichennaya sreda (Mif+/PvP/Boi). Chast UI zablokirovana."
L["PerfAlert"] = "Preduprezhdenie: vremya vipolneniya previshaet porog!"

L["Cmd_Config"] = "otkryt nastroiki"
L["Cmd_Cache"] = "ochistit kesh"
L["Cmd_Version"] = "pokazat versiu"
L["Cmd_Help"] = "Spravka po komandam"
L["Clear All"] = "Ochistit vse"
L["Toggle Debug Mode"] = "Perekluchit rezhim otladki"
L["Combat Ended"] = "Boi okonchen, rezhim audita snizhen."
L["Engine Started"] = "Dvizhok Polnoch 12.0 zapushchen."
L["Audit Report"] = "Otchet ob audite predmeta"
L["Scanning Auras"] = "Skanirovanie aur 12.0 dlya yedinitsy %s ..."
L["Settings_Enable_Desc"] = "Vkluchit/vykluchit vse podskazki LorisID"
L["Settings_Debug_Desc"] = "Vkluchit vyvod audita C_AddOnProfiler 12.0"
L["Settings_Cache_Desc"] = "Snizit zaderzhki v gorodakh/krupnykh srazheniyakh"
L["Settings_CacheSize_Desc"] = "LRU-udalenie pri prevyshenii etogo kolichestva"
L["Settings_Threshold_Desc"] = "Preduprezhdat v chat pri prevyshenii vremeni"
L["Items Count"] = "elementov"
end

-- =========================================================
-- 10. 葡萄牙语 (ptBR)
-- =========================================================
if locale == "ptBR" then
L["AddonName"] = "LorisID |cFF00FF00[Meia-Noite]|r"
L["Init_Loaded"] = "LorisID inicializado. API Meia-Noite 12.0 pronta."
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r Configuracoes"

L["Control"] = "Controle"
L["EnableModule"] = "Ativar modulo"
L["Debug Mode"] = "Modo depuracao"
L["ID Display Settings"] = "Configuracoes de exibicao de ID"
L["Item"] = "Item"
L["Spell"] = "Magia"
L["Petspell"] = "Magia do mascote"
L["Unit"] = "Unidade"
L["Quest"] = "Missao"
L["Achievement"] = "Conquista"
L["Currency"] = "Moeda"
L["Mount"] = "Montaria"
L["Toy"] = "Brinquedo"
L["Talent"] = "Talento"
L["Companion"] = "Companheiro"
L["Object"] = "Objeto do mundo"
L["Battlepet"] = "Mascote de batalha"
L["Instance"] = "Instancia"
L["Recipe"] = "Receita"
L["Macro"] = "Macro"
L["Pvp"] = "Briga JxJ"
L["Minimap"] = "Minimapa"
L["Icon"] = "Icone"
L["Set"] = "Conjunto"
L["Visual"] = "Transmogrificacao"
L["Performance & Cache"] = "Desempenho e cache"
L["Enable high-performance LRU cache"] = "Ativar cache LRU de alto desempenho"
L["Cache Size Limit"] = "Limite de tamanho do cache"
L["Performance Audit Warning Threshold"] = "Limite de alerta de auditoria de desempenho"

L["Spell ID"] = "ID da magia"
L["Petspell ID"] = "ID da magia do mascote"
L["Item ID"] = "ID do item"
L["Unit ID"] = "ID da unidade"
L["NPC ID"] = "ID do NPC"
L["Quest ID"] = "ID da missao"
L["Achievement ID"] = "ID da conquista"
L["Currency ID"] = "ID da moeda"
L["Mount ID"] = "ID da montaria"
L["Toy ID"] = "ID do brinquedo"
L["Companion ID"] = "ID do companheiro"
L["Object ID"] = "ID do objeto"
L["Battlepet ID"] = "ID do mascote"
L["Instance ID"] = "ID da instancia"
L["Recipe ID"] = "ID da receita"
L["Macro ID"] = "ID da macro"
L["Pvp ID"] = "ID da briga JxJ"
L["Minimap ID"] = "ID do minimapa"
L["Icon ID"] = "ID do icone"
L["Talent ID"] = "ID do talento"
L["Set ID"] = "ID do conjunto"
L["Equipment Set ID"] = "ID do conjunto de equipamento"
L["Visual ID"] = "ID de transmogrificacao"

L["Item_Level"] = "Nivel do item"
L["Stack_Size"] = "Tamanho da pilha"
L["Item_Price"] = "Preco de venda"
L["Unit_Classification"] = "Classificacao"
L["GUID"] = "GUID"
L["Target of"] = "Alvo de"
L["Expansion"] = "Expansao"
L["Count"] = "Quantidade"
L["SecretValueBlocked"] = "Bloqueado: tentativa de acessar valor secreto em combate."
L["RestrictedEnvironment"] = "Ambiente restrito (Mitica+/JxJ/Combate). Alguns elementos bloqueados."
L["PerfAlert"] = "Alerta de desempenho: tempo de execucao excede o limite!"

L["Cmd_Config"] = "abrir configuracoes"
L["Cmd_Cache"] = "limpar cache"
L["Cmd_Version"] = "exibir versao"
L["Cmd_Help"] = "Ajuda de comandos"
L["Clear All"] = "Limpar tudo"
L["Toggle Debug Mode"] = "Alternar modo depuracao"
L["Combat Ended"] = "Combate encerrado, modo de auditoria desativado."
L["Engine Started"] = "Motor Meia-Noite 12.0 iniciado."
L["Audit Report"] = "Relatorio de auditoria do item"
L["Scanning Auras"] = "Escaneando auras 12.0 para unidade %s ..."
L["Settings_Enable_Desc"] = "Ativar/desativar todas as dicas do LorisID"
L["Settings_Debug_Desc"] = "Ativar saida de auditoria C_AddOnProfiler 12.0"
L["Settings_Cache_Desc"] = "Reduzir lag em cidades/combate em larga escala"
L["Settings_CacheSize_Desc"] = "Remocao LRU ativada acima desta quantidade"
L["Settings_Threshold_Desc"] = "Avisar no chat se o tempo de execucao exceder"
L["Items Count"] = "itens"
end

-- =========================================================
-- 11. 意大利语 (itIT)
-- =========================================================
if locale == "itIT" then
L["AddonName"] = "LorisID |cFF00FF00[Mezzanotte]|r"
L["Init_Loaded"] = "LorisID inizializzato. API Mezzanotte 12.0 pronta."
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r Impostazioni"

L["Control"] = "Controllo"
L["EnableModule"] = "Attiva modulo"
L["Debug Mode"] = "Modalita debug"
L["ID Display Settings"] = "Impostazioni visualizzazione ID"
L["Item"] = "Oggetto"
L["Spell"] = "Incantesimo"
L["Petspell"] = "Incantesimo del famiglio"
L["Unit"] = "Unita"
L["Quest"] = "Missione"
L["Achievement"] = "Impresa"
L["Currency"] = "Valuta"
L["Mount"] = "Cavalcatura"
L["Toy"] = "Giocattolo"
L["Talent"] = "Talento"
L["Companion"] = "Compagno"
L["Object"] = "Oggetto di gioco"
L["Battlepet"] = "Mascotte da battaglia"
L["Instance"] = "Istanza"
L["Recipe"] = "Ricetta"
L["Macro"] = "Macro"
L["Pvp"] = "Rissa GvG"
L["Minimap"] = "Minimappa"
L["Icon"] = "Icona"
L["Set"] = "Set"
L["Visual"] = "Trasmogrificazione"
L["Performance & Cache"] = "Prestazioni e cache"
L["Enable high-performance LRU cache"] = "Attiva cache LRU ad alte prestazioni"
L["Cache Size Limit"] = "Limite dimensione cache"
L["Performance Audit Warning Threshold"] = "Soglia di avviso audit prestazioni"

L["Spell ID"] = "ID incantesimo"
L["Petspell ID"] = "ID incantesimo del famiglio"
L["Item ID"] = "ID oggetto"
L["Unit ID"] = "ID unita"
L["NPC ID"] = "ID PNG"
L["Quest ID"] = "ID missione"
L["Achievement ID"] = "ID impresa"
L["Currency ID"] = "ID valuta"
L["Mount ID"] = "ID cavalcatura"
L["Toy ID"] = "ID giocattolo"
L["Companion ID"] = "ID compagno"
L["Object ID"] = "ID oggetto"
L["Battlepet ID"] = "ID mascotte"
L["Instance ID"] = "ID istanza"
L["Recipe ID"] = "ID ricetta"
L["Macro ID"] = "ID macro"
L["Pvp ID"] = "ID rissa GvG"
L["Minimap ID"] = "ID minimappa"
L["Icon ID"] = "ID icona"
L["Talent ID"] = "ID talento"
L["Set ID"] = "ID set"
L["Equipment Set ID"] = "ID set di equipaggiamento"
L["Visual ID"] = "ID trasmogrificazione"

L["Item_Level"] = "Livello oggetto"
L["Stack_Size"] = "Dimensione pila"
L["Item_Price"] = "Prezzo di vendita"
L["Unit_Classification"] = "Classificazione"
L["GUID"] = "GUID"
L["Target of"] = "Bersaglio di"
L["Expansion"] = "Espansione"
L["Count"] = "Conteggio"
L["SecretValueBlocked"] = "Bloccato: tentativo di operare su un valore segreto in combattimento."
L["RestrictedEnvironment"] = "Ambiente ristretto (Mitica+/GvG/Combattimento). Alcuni elementi bloccati."
L["PerfAlert"] = "Avviso prestazioni: il tempo di esecuzione supera la soglia!"

L["Cmd_Config"] = "apri impostazioni"
L["Cmd_Cache"] = "svuota cache"
L["Cmd_Version"] = "mostra versione"
L["Cmd_Help"] = "Guida comandi"
L["Clear All"] = "Svuota tutto"
L["Toggle Debug Mode"] = "Attiva/disattiva modalita debug"
L["Combat Ended"] = "Combattimento finito, modalita audit ridotta."
L["Engine Started"] = "Motore Mezzanotte 12.0 avviato."
L["Audit Report"] = "Report audit oggetto"
L["Scanning Auras"] = "Scansione aure 12.0 per unita %s ..."
L["Settings_Enable_Desc"] = "Attiva/disattiva tutti i tooltip LorisID"
L["Settings_Debug_Desc"] = "Attiva output audit C_AddOnProfiler 12.0"
L["Settings_Cache_Desc"] = "Riduci lag in citta/combattimenti su larga scala"
L["Settings_CacheSize_Desc"] = "Rimozione LRU attivata sopra questo numero"
L["Settings_Threshold_Desc"] = "Avvisa in chat se il tempo di esecuzione supera"
L["Items Count"] = "elementi"
end