local addonName, ns =...

-- =========================================================
-- 1. 本地化元表 (12.0 fallback 机制)
-- =========================================================
local L = setmetatable({}, {
    __index = function(t, k)
        return k
    end
})

ns.L = L

local locale = GetLocale()

-- =========================================================
-- 2. 默认语言: 英文 (enUS / enGB)
-- =========================================================
L["AddonName"] = "LorisID |cFF00FF00[Midnight]|r"
L["Init_Loaded"] = "LorisID initialized. Midnight 12.0 API ready."
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r Settings"

L["Control"] = "Control"
L["EnableModule"] = "Enable Module"
L["Debug Mode"] = "Debug Mode"
L["ID Display Settings"] = "ID Display Settings"
L["Item"] = "Item"
L["Spell"] = "Spell"
L["Unit"] = "Unit"
L["Quest"] = "Quest"
L["Achievement"] = "Achievement"
L["Currency"] = "Currency"
L["Mount"] = "Mount"
L["Toy"] = "Toy"
L["Talent"] = "Talent"
L["Companion"] = "Companion"
L["Object"] = "Object"
L["Battlepet"] = "Battle Pet"
L["Instance"] = "Instance"
L["Recipe"] = "Recipe"
L["Macro"] = "Macro"
L["Pvp"] = "PvP Brawl"
L["Minimap"] = "Minimap"
L["Icon"] = "Icon"
L["Set"] = "Equipment Set"
L["Visual"] = "Visual"
L["Performance & Cache"] = "Performance & Cache"
L["Enable high-performance LRU cache"] = "Enable high-performance LRU cache"
L["Cache Size Limit"] = "Cache Size Limit"
L["Performance Audit Warning Threshold"] = "Performance Audit Warning Threshold"

L["Spell ID"] = "Spell ID"
L["Item ID"] = "Item ID"
L["Unit ID"] = "Unit ID"
L["NPC ID"] = "NPC ID"
L["Quest ID"] = "Quest ID"
L["Achievement ID"] = "Achievement ID"
L["Currency ID"] = "Currency ID"
L["Mount ID"] = "Mount ID"
L["Toy ID"] = "Toy ID"
L["Companion ID"] = "Companion ID"
L["Object ID"] = "Object ID"
L["Battlepet ID"] = "Battle Pet ID"
L["Instance ID"] = "Instance ID"
L["Recipe ID"] = "Recipe ID"
L["Macro ID"] = "Macro ID"
L["Pvp ID"] = "PvP Brawl ID"
L["Minimap ID"] = "Minimap ID"
L["Icon ID"] = "Icon ID"
L["Talent ID"] = "Talent ID"
L["Set ID"] = "Equipment Set ID"
L["Equipment Set ID"] = "Equipment Set ID"
L["Visual ID"] = "Visual ID"

L["Item_Level"] = "Item Level"
L["Stack_Size"] = "Stack Size"
L["Item_Price"] = "Sell Price"
L["Unit_Classification"] = "Classification"
L["GUID"] = "GUID"
L["Target of"] = "Target of"
L["Expansion"] = "Expansion"
L["Count"] = "Count"
L["SecretValueBlocked"] = "Action Blocked: Logic attempted to operate on a Secret Value during combat."
L["RestrictedEnvironment"] = "Restricted Environment (Mythic+/PvP/Combat). Some UI elements are locked."
L["PerfAlert"] = "Performance Alert: execution time exceeds threshold!"

L["Cmd_Config"] = "open settings panel"
L["Cmd_Cache"] = "clear data cache"
L["Cmd_Version"] = "display version info"
L["Cmd_Help"] = "Command Line Help"
L["Clear All"] = "Clear All"
L["Toggle Debug Mode"] = "Toggle Debug Mode"
L["Combat Ended"] = "Combat ended, security audit mode downgraded."
L["Engine Started"] = "12.0 Midnight Core Engine Started."
L["Audit Report"] = "Item Audit Report"
L["Scanning Auras"] = "Scanning 12.0 Aura Data for unit %s..."
L["Settings_Enable_Desc"] = "Enable or disable all LorisID tooltips"
L["Settings_Debug_Desc"] = "Enable 12.0 C_AddOnProfiler audit output"
L["Settings_Cache_Desc"] = "Significantly reduce lag in cities or large scale combat"
L["Settings_CacheSize_Desc"] = "LRU eviction triggers above this count"
L["Settings_Threshold_Desc"] = "Warn in chat if execution time exceeds this value"
L["Items Count"] = "items"

-- =========================================================
-- 3. 简体中文 (zhCN)
-- =========================================================
if locale == "zhCN" then

L["AddonName"] = "LorisID |cFF00FF00[至暗之夜]|r"
L["Init_Loaded"] = "LorisID 已加载。至暗之夜 12.0 API 已就绪。"
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r 插件设置"

L["Control"] = "控制"
L["EnableModule"] = "启用模块"
L["Debug Mode"] = "调试模式"
L["ID Display Settings"] = "ID 显示设置"
L["Item"] = "物品"
L["Spell"] = "法术"
L["Unit"] = "单位"
L["Quest"] = "任务"
L["Achievement"] = "成就"
L["Currency"] = "货币"
L["Mount"] = "坐骑"
L["Toy"] = "玩具"
L["Talent"] = "天赋"
L["Companion"] = "伙伴"
L["Object"] = "游戏对象"
L["Battlepet"] = "对战宠物"
L["Instance"] = "副本"
L["Recipe"] = "配方"
L["Macro"] = "宏"
L["Pvp"] = "PvP乱斗"
L["Minimap"] = "小地图"
L["Icon"] = "图标"
L["Set"] = "套装"
L["Visual"] = "幻化"
L["Performance & Cache"] = "性能与缓存"
L["Enable high-performance LRU cache"] = "启用高性能 LRU 缓存"
L["Cache Size Limit"] = "缓存容量上限"
L["Performance Audit Warning Threshold"] = "性能审计警告阈值"

L["Spell ID"] = "技能 ID"
L["Item ID"] = "物品 ID"
L["Unit ID"] = "单位 ID"
L["NPC ID"] = "NPC ID"
L["Quest ID"] = "任务 ID"
L["Achievement ID"] = "成就 ID"
L["Currency ID"] = "货币 ID"
L["Mount ID"] = "坐骑 ID"
L["Toy ID"] = "玩具 ID"
L["Companion ID"] = "伙伴 ID"
L["Object ID"] = "对象 ID"
L["Battlepet ID"] = "宠物物种 ID"
L["Instance ID"] = "副本 ID"
L["Recipe ID"] = "配方 ID"
L["Macro ID"] = "宏 ID"
L["Pvp ID"] = "乱斗 ID"
L["Minimap ID"] = "小地图 ID"
L["Icon ID"] = "图标 ID"
L["Talent ID"] = "天赋 ID"
L["Set ID"] = "套装 ID"
L["Equipment Set ID"] = "套装 ID"
L["Visual ID"] = "幻化 ID"

L["Item_Level"] = "装等"
L["Stack_Size"] = "堆叠上限"
L["Item_Price"] = "售价"
L["Unit_Classification"] = "分类"
L["GUID"] = "唯一标识(GUID)"
L["Target of"] = "目标的目标"
L["Expansion"] = "归属版本"
L["Count"] = "层数"
L["SecretValueBlocked"] = "动作被拦截：逻辑尝试在战斗中对「秘密值」进行运算。"
L["RestrictedEnvironment"] = "当前处于受限环境（大秘境/竞技场/战斗中）。部分 UI 逻辑已锁定。"
L["PerfAlert"] = "性能警告：插件执行耗时超过阈值！"

L["Cmd_Config"] = "打开设置面板"
L["Cmd_Cache"] = "清除数据缓存"
L["Cmd_Version"] = "显示版本信息"
L["Cmd_Help"] = "命令行帮助"
L["Clear All"] = "清理全部"
L["Toggle Debug Mode"] = "切换调试模式"
L["Combat Ended"] = "战斗结束，安全审计模式降级。"
L["Engine Started"] = "12.0 至暗之夜核心控制引擎启动成功。"
L["Audit Report"] = "物品详细审计报告"
L["Scanning Auras"] = "正在扫描单位 %s 的 12.0 光环数据..."
L["Settings_Enable_Desc"] = "开启或关闭 LorisID 的全部提示功能"
L["Settings_Debug_Desc"] = "开启 12.0 C_AddOnProfiler 性能审计输出"
L["Settings_Cache_Desc"] = "显著降低在大城市或大规模战斗中的卡顿"
L["Settings_CacheSize_Desc"] = "超过此数量将触发 LRU 淘汰算法"
L["Settings_Threshold_Desc"] = "单次函数耗时超过此值将在聊天框输出警告"
L["Items Count"] = "项"
end

-- =========================================================
-- 4. 繁体中文 (zhTW)
-- =========================================================
if locale == "zhTW" then
L["AddonName"] = "LorisID |cFF00FF00[至暗之夜]|r"
L["Init_Loaded"] = "LorisID 已加載。至暗之夜 12.0 API 已就緒。"
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r 插件設置"

L["Control"] = "控制"
L["EnableModule"] = "啟用模組"
L["Debug Mode"] = "除錯模式"
L["ID Display Settings"] = "ID 顯示設置"
L["Item"] = "物品"
L["Spell"] = "法術"
L["Unit"] = "單位"
L["Quest"] = "任務"
L["Achievement"] = "成就"
L["Currency"] = "貨幣"
L["Mount"] = "坐騎"
L["Toy"] = "玩具"
L["Talent"] = "天賦"
L["Companion"] = "夥伴"
L["Object"] = "遊戲對象"
L["Battlepet"] = "戰寵"
L["Instance"] = "副本"
L["Recipe"] = "配方"
L["Macro"] = "巨集"
L["Pvp"] = "PvP亂鬥"
L["Minimap"] = "小地圖"
L["Icon"] = "圖標"
L["Set"] = "套裝"
L["Visual"] = "幻化"
L["Performance & Cache"] = "性能與緩存"
L["Enable high-performance LRU cache"] = "啟用高性能 LRU 緩存"
L["Cache Size Limit"] = "緩存容量上限"
L["Performance Audit Warning Threshold"] = "性能審計警告閾值"

L["Spell ID"] = "技能 ID"
L["Item ID"] = "物品 ID"
L["Unit ID"] = "單位 ID"
L["NPC ID"] = "NPC ID"
L["Quest ID"] = "任務 ID"
L["Achievement ID"] = "成就 ID"
L["Currency ID"] = "貨幣 ID"
L["Mount ID"] = "坐騎 ID"
L["Toy ID"] = "玩具 ID"
L["Companion ID"] = "夥伴 ID"
L["Object ID"] = "對象 ID"
L["Battlepet ID"] = "寵物物種 ID"
L["Instance ID"] = "副本 ID"
L["Recipe ID"] = "配方 ID"
L["Macro ID"] = "巨集 ID"
L["Pvp ID"] = "亂鬥 ID"
L["Minimap ID"] = "小地圖 ID"
L["Icon ID"] = "圖標 ID"
L["Talent ID"] = "天賦 ID"
L["Set ID"] = "套裝 ID"
L["Equipment Set ID"] = "套裝 ID"
L["Visual ID"] = "幻化 ID"

L["Item_Level"] = "物品等級"
L["Stack_Size"] = "堆疊上限"
L["Item_Price"] = "售價"
L["Unit_Classification"] = "分類"
L["GUID"] = "唯一標識(GUID)"
L["Target of"] = "目標的目標"
L["Expansion"] = "歸屬版本"
L["Count"] = "層數"
L["SecretValueBlocked"] = "動作被攔截：邏輯嘗試在戰鬥中對「秘密值」進行運算。"
L["RestrictedEnvironment"] = "當前處於受限環境（大秘境/競技場/戰鬥中）。部分 UI 邏輯已鎖定。"
L["PerfAlert"] = "性能警告：插件執行耗時超過閾值！"

L["Cmd_Config"] = "打開設置面板"
L["Cmd_Cache"] = "清除數據緩存"
L["Cmd_Version"] = "顯示版本信息"
L["Cmd_Help"] = "命令行幫助"
L["Clear All"] = "清理全部"
L["Toggle Debug Mode"] = "切換除錯模式"
L["Combat Ended"] = "戰鬥結束，安全審計模式降級。"
L["Engine Started"] = "12.0 至暗之夜核心控制引擎啟動成功。"
L["Audit Report"] = "物品詳細審計報告"
L["Scanning Auras"] = "正在掃描單位 %s 的 12.0 光環數據..."
L["Settings_Enable_Desc"] = "開啟或關閉 LorisID 的全部提示功能"
L["Settings_Debug_Desc"] = "開啟 12.0 C_AddOnProfiler 性能審計輸出"
L["Settings_Cache_Desc"] = "顯著降低在大城市或大規模戰鬥中的卡頓"
L["Settings_CacheSize_Desc"] = "超過此數量將觸發 LRU 淘汰算法"
L["Settings_Threshold_Desc"] = "單次函數耗時超過此值將在聊天框輸出警告"
L["Items Count"] = "項"
end

-- =========================================================
-- 5. 韩语 (koKR)
-- =========================================================
if locale == "koKR" then
L["AddonName"] = "LorisID |cFF00FF00[한밤]|r"
L["Init_Loaded"] = "LorisID 초기화 완료. 한밤 12.0 API 준비됨."
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r 설정"

L["Control"] = "제어"
L["EnableModule"] = "모듈 활성화"
L["Debug Mode"] = "디버그 모드"
L["ID Display Settings"] = "ID 표시 설정"
L["Item"] = "아이템"
L["Spell"] = "주문"
L["Unit"] = "유닛"
L["Quest"] = "퀘스트"
L["Achievement"] = "업적"
L["Currency"] = "화폐"
L["Mount"] = "탈것"
L["Toy"] = "장난감"
L["Talent"] = "특성"
L["Companion"] = "동료"
L["Object"] = "게임 오브젝트"
L["Battlepet"] = "애완동물"
L["Instance"] = "인스턴스"
L["Recipe"] = "제조법"
L["Macro"] = "매크로"
L["Pvp"] = "PvP 난투"
L["Minimap"] = "미니맵"
L["Icon"] = "아이콘"
L["Set"] = "장비 세트"
L["Visual"] = "형상변환"
L["Performance & Cache"] = "성능 및 캐시"
L["Enable high-performance LRU cache"] = "고성능 LRU 캐시 활성화"
L["Cache Size Limit"] = "캐시 크기 제한"
L["Performance Audit Warning Threshold"] = "성능 감사 경고 임계값"

L["Spell ID"] = "주문 ID"
L["Item ID"] = "아이템 ID"
L["Unit ID"] = "유닛 ID"
L["NPC ID"] = "NPC ID"
L["Quest ID"] = "퀘스트 ID"
L["Achievement ID"] = "업적 ID"
L["Currency ID"] = "화폐 ID"
L["Mount ID"] = "탈것 ID"
L["Toy ID"] = "장난감 ID"
L["Companion ID"] = "동료 ID"
L["Object ID"] = "오브젝트 ID"
L["Battlepet ID"] = "애완동물 종 ID"
L["Instance ID"] = "인스턴스 ID"
L["Recipe ID"] = "제조법 ID"
L["Macro ID"] = "매크로 ID"
L["Pvp ID"] = "난투 ID"
L["Minimap ID"] = "미니맵 ID"
L["Icon ID"] = "아이콘 ID"
L["Talent ID"] = "특성 ID"
L["Set ID"] = "장비 세트 ID"
L["Equipment Set ID"] = "장비 세트 ID"
L["Visual ID"] = "형상변환 ID"

L["Item_Level"] = "아이템 레벨"
L["Stack_Size"] = "최대 겹침"
L["Item_Price"] = "판매 가격"
L["Unit_Classification"] = "분류"
L["GUID"] = "GUID"
L["Target of"] = "대상의 대상"
L["Expansion"] = "확장팩"
L["Count"] = "중첩"
L["SecretValueBlocked"] = "차단됨: 전투 중 비밀 값 연산 시도."
L["RestrictedEnvironment"] = "제한 환경 (신화+/PvP/전투). 일부 UI 잠김."
L["PerfAlert"] = "성능 경고: 실행 시간이 임계값 초과!"

L["Cmd_Config"] = "설정 패널 열기"
L["Cmd_Cache"] = "데이터 캐시 삭제"
L["Cmd_Version"] = "버전 정보 표시"
L["Cmd_Help"] = "명령어 도움말"
L["Clear All"] = "모두 삭제"
L["Toggle Debug Mode"] = "디버그 모드 전환"
L["Combat Ended"] = "전투 종료, 보안 감사 모드 해제."
L["Engine Started"] = "12.0 한밤 코어 엔진 시작됨."
L["Audit Report"] = "아이템 감사 보고서"
L["Scanning Auras"] = "유닛 %s 의 12.0 오라 데이터 스캔 중..."
L["Settings_Enable_Desc"] = "모든 LorisID 툴팁 활성화/비활성화"
L["Settings_Debug_Desc"] = "12.0 C_AddOnProfiler 감사 출력 활성화"
L["Settings_Cache_Desc"] = "도시 또는 대규모 전투에서 렉 감소"
L["Settings_CacheSize_Desc"] = "이 개수 초과 시 LRU 제거 작동"
L["Settings_Threshold_Desc"] = "실행 시간이 이 값을 초과하면 채팅에 경고"
L["Items Count"] = "개"
end

-- =========================================================
-- 6. 德语 (deDE)
-- =========================================================
if locale == "deDE" then
L["AddonName"] = "LorisID |cFF00FF00[Mitternacht]|r"
L["Init_Loaded"] = "LorisID initialisiert. Mitternacht 12.0 API bereit."
L["Settings"] = "|cff00ff00Loris|r|cffffd700ID|r Einstellungen"

L["Control"] = "Steuerung"
L["EnableModule"] = "Modul aktivieren"
L["Debug Mode"] = "Debug-Modus"
L["ID Display Settings"] = "ID-Anzeigeeinstellungen"
L["Item"] = "Gegenstand"
L["Spell"] = "Zauber"
L["Unit"] = "Einheit"
L["Quest"] = "Quest"
L["Achievement"] = "Erfolg"
L["Currency"] = "Wahrung"
L["Mount"] = "Reittier"
L["Toy"] = "Spielzeug"
L["Talent"] = "Talent"
L["Companion"] = "Begleiter"
L["Object"] = "Spielobjekt"
L["Battlepet"] = "Kampfhaustier"
L["Instance"] = "Instanz"
L["Recipe"] = "Rezept"
L["Macro"] = "Makro"
L["Pvp"] = "PvP-Schlacht"
L["Minimap"] = "Minikarte"
L["Icon"] = "Symbol"
L["Set"] = "Ausrustungsset"
L["Visual"] = "Transmogrifikation"
L["Performance & Cache"] = "Leistung & Cache"
L["Enable high-performance LRU cache"] = "Hochleistungs-LRU-Cache aktivieren"
L["Cache Size Limit"] = "Cache-Großenlimit"
L["Performance Audit Warning Threshold"] = "Leistungsprufungs-Warnschwelle"

L["Spell ID"] = "Zauber-ID"
L["Item ID"] = "Gegenstands-ID"
L["Unit ID"] = "Einheiten-ID"
L["NPC ID"] = "NPC-ID"
L["Quest ID"] = "Quest-ID"
L["Achievement ID"] = "Erfolgs-ID"
L["Currency ID"] = "Wahrungs-ID"
L["Mount ID"] = "Reittier-ID"
L["Toy ID"] = "Spielzeug-ID"
L["Companion ID"] = "Begleiter-ID"
L["Object ID"] = "Objekt-ID"
L["Battlepet ID"] = "Kampfhaustier-ID"
L["Instance ID"] = "Instanz-ID"
L["Recipe ID"] = "Rezept-ID"
L["Macro ID"] = "Makro-ID"
L["Pvp ID"] = "PvP-Schlacht-ID"
L["Minimap ID"] = "Minikarten-ID"
L["Icon ID"] = "Symbol-ID"
L["Talent ID"] = "Talent-ID"
L["Set ID"] = "Ausrustungsset-ID"
L["Equipment Set ID"] = "Ausrustungsset-ID"
L["Visual ID"] = "Transmogrifikations-ID"

L["Item_Level"] = "Gegenstandsstufe"
L["Stack_Size"] = "Stapelgroße"
L["Item_Price"] = "Verkaufspreis"
L["Unit_Classification"] = "Klassifizierung"
L["GUID"] = "GUID"
L["Target of"] = "Ziel von"
L["Expansion"] = "Erweiterung"
L["Count"] = "Anzahl"
L["SecretValueBlocked"] = "Blockiert: Versuch, im Kampf auf geheimen Wert zuzugreifen."
L["RestrictedEnvironment"] = "Eingeschrankte Umgebung (Mythisch+/PvP/Kampf). Einige UI-Elemente gesperrt."
L["PerfAlert"] = "Leistungswarnung: Ausfuhrungszeit uberschreitet Schwelle!"

L["Cmd_Config"] = "Einstellungen offnen"
L["Cmd_Cache"] = "Daten-Cache leeren"
L["Cmd_Version"] = "Versionsinfo anzeigen"
L["Cmd_Help"] = "Befehlshilfe"
L["Clear All"] = "Alle leeren"
L["Toggle Debug Mode"] = "Debug-Modus umschalten"
L["Combat Ended"] = "Kampf beendet, Sicherheitsprufungsmodus herabgestuft."
L["Engine Started"] = "12.0 Mitternacht Core-Engine gestartet."
L["Audit Report"] = "Gegenstandsprufbericht"
L["Scanning Auras"] = "Scanne 12.0 Aura-Daten fur Einheit %s ..."
L["Settings_Enable_Desc"] = "Alle LorisID-Tooltips aktivieren/deaktivieren"
L["Settings_Debug_Desc"] = "12.0 C_AddOnProfiler-Prufausgabe aktivieren"
L["Settings_Cache_Desc"] = "Verzogerung in Stadten/großen Kampfen reduzieren"
L["Settings_CacheSize_Desc"] = "LRU-Entfernung wird oberhalb dieser Anzahl ausgelost"
L["Settings_Threshold_Desc"] = "Warnung im Chat, wenn Ausfuhrungszeit uberschritten"
L["Items Count"] = "Eintrage"
end
